### PR TITLE
Bump Acorn and Minimist

### PR DESCRIPTION
**Pull request by meganyin13**
Fix the security vulnerability.
My changes in #78 were merged in about 2 hours ago but the changes still haven't shown up on the main site. I'm not sure if this is the issue.

### CODE REVIEW

**Comment by SamChou19815** [comment]
@meganyin13 deploy command seems to be broken in the new docusaurus version.
See https://github.com/facebook/docusaurus/pull/2496

**Comment by meganyin13** [comment]
Should I wait for that PR to get merged in?

**Comment by SamChou19815** [comment]
@meganyin13 you should probably downgrade docusaurus to alpha-48 for now :(

**Comment by yangshun** [comment]
Sorry about that. We'll publish hotfix today

**Pull request merged**
