### PR TITLE
Remove all lecture notes from last semester

### PR DESCRIPTION
**Pull request by meganyin13**
Remove the notes from last semester because we want students to follow along as the course progresses. Also in some later lecture examples they may be able to get answers for earlier assignments. 

The lecture notes are saved in the Trends shared folder so we can add them back in as we go.

### CODE REVIEW

**Comment by SamChou19815** [comment]
Should we put the notes in a separate folder instead of removing them?

**Comment by meganyin13** [comment]
> Should we put the notes in a separate folder in the repo instead of removing them? People can find out from git history anyways.

This is a good idea. I'll put it in a new folder `old-docs`.

**Comment by SamChou19815** [comment]
If we expect each semester's content to be slightly different and we want to keep the old one, we can try the versioning feature of docusaurus: https://v2.docusaurus.io/docs/versioning
Not push blocking for this PR.

**Comment by meganyin13** [comment]
Ok I will look into versioning, but for now I think this is good to merge.

**Pull request merged**
